### ISSUE TITLE
Signature plug in manquante

### ISSUE THREAD

**Issue by Chris9212** [NebzHB/jeedom_docs#1]
Bonjour,
Après reset de ma smart et importation sauvegarde, le plug in homebridge n'est plus signé et les dépendances ne s'installent plus.
Debug : "W: The repository 'http://repo.jeedom.com/odroid dists/stable/main/binary-arm64/ Release' is not signed."
Pouvez vous rétablir la situation s'il vous plait ?
En pj ma facture d'achat du plug in.
Merci
Cordialement
[Achat plugin Jeedom numéro PAY-7LW73463J7701461LLH4D3SI.txt](https://github.com/NebzHB/jeedom_docs/files/3013887/Achat.plugin.Jeedom.numero.PAY-7LW73463J7701461LLH4D3SI.txt)

**Comment by NebzHB** [comment]
fixed by jeedom
