### ISSUE TITLE
Homebridge statut NOK

### ISSUE THREAD

**Issue by AISANCE** [NebzHB/jeedom_docs#10]
Bonjour,
Je tente d’installer le plugin depuis hier mais le statut du demon reste NOK.
J’ai relancé les dépendances
Redemarer le demon
Supprimé et réinstallé le plugin mais rien ne change.

Message d’erreur:
homebridge Attention je pense qu’il y a un soucis avec le démon que j’ai relancé plus de 3 fois consécutivement

Merci d’avance pour votre aide

Christophe

**Comment by NebzHB** [comment]
Bonjour,

merci pour votre message, mais sans log, je ne peux pas vous aider.
