### ISSUE TITLE
homebridge dependances

### ISSUE THREAD

**Issue by transervice** [NebzHB/jeedom_docs#11]
Bonjour, 
Impossible d'installer les dépendances
Le log est le suivant :
Log du plugin

== Jeedom 3.3.47 sur Debian GNU/Linux 9.4 (stretch)/arm64/aarch64/64bits aka 'smart' avec nodeJS v4.8.2 et jsonrpc:enable et homebridge (stable) 2020-04-19 21:10:05
======================================================================
== 23/04/2020 08:55:05 == Installation des dépendances de homebridge
======================================================================
[  0% ] : Vérification des droits...
[  9% ] : Vérification des droits : [  OK  ]
[ 10% ] : Prérequis...
Désactivation de la source repo.jeedom.com !
[ 19% ] : Prérequis : [  OK  ]
[ 20% ] : Mise à jour APT et installation des packages nécessaires...
[ 29% ] : Mise à jour APT et installation des packages nécessaires : [  OK  ]
[ 30% ] : Vérification de la version de NodeJS installée...
Version actuelle : v4.8.2
[ 39% ] : Vérification de la version de NodeJS installée : [  OK  ]
[ 40% ] : Installation de NodeJS 12...
KO, version obsolète à upgrader
Suppression du Nodejs existant et installation du paquet recommandé
--45%
Utilisation du dépot officiel
Version après install : v4.8.2
[ 44% ] : Installation de NodeJS 12 : [  OK  ]
[ 45% ] : Installation de npm car non présent...
[ 49% ] : Installation de npm car non présent : [ERREUR]
[ 50% ] : Nettoyage anciens modules...
[ 59% ] : Nettoyage anciens modules : [  OK  ]
[ 60% ] : Installation de Homebridge master, veuillez patienter svp...
[ 79% ] : Installation de Homebridge master, veuillez patienter svp : [ERREUR]
[ 80% ] : Configuration Avahi...
Désactivation de avahi-daemon au démarrage...(il démarrera avec le daemon (on contourne le bug de la Smart du 1 jan 1970))
[ 89% ] : Configuration Avahi : [  OK  ]
[ 90% ] : Nettoyage 1/2...
[ 94% ] : Nettoyage 1/2 : [  OK  ]
[ 95% ] : Nettoyage 2/2...
Réactivation de la source repo.jeedom.com qu'on avait désactivé !
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
[ 99% ] : Nettoyage 2/2 : [  OK  ]
[100% ] : Terminé !
======================================================================
== KO == Erreur d'Installation
======================================================================
== Erreur à l'étape : Installation de npm car non présent
== Ligne 155
== La commande `sudo DEBIAN_FRONTEND=noninteractive apt-get install -y npm' pose problème
== Le code de retour est 100
== Le message d'erreur :
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
npm : Depends: nodejs (>= 6.11~) but 4.8.2~dfsg-1 is to be installed
Depends: node-abbrev (>= 1.1.1~) but 1.0.9-1 is to be installed
Depends: node-ansi-regex (>= 3.0~) but 2.0.0-1 is to be installed
Depends: node-cacache (>= 10.0.4~) but it is not going to be installed
Depends: node-config-chain (>= 1.1.11~) but it is not going to be installed
Depends: node-glob (>= 7.1.2~) but 7.1.1-1 is to be installed
Depends: node-hosted-git-info (>= 2.6~) but 2.1.5-1 is to be installed
Depends: node-ini (>= 1.3.5~) but 1.1.0-1 is to be installed
Depends: node-npm-package-arg but it is not going to be installed
Depends: node-jsonstream (>= 1.3.2~) but 1.0.3-4 is to be installed
Depends: node-libnpx (>= 10.0.1~) but it is not going to be installed
Depends: node-lockfile (>= 1.0.3~) but 0.4.1-1 is to be installed
Depends: node-lru-cache (>= 4.1.1~) but 4.0.2-1 is to be installed
Depends: node-move-concurrently (>= 1.0.1~) but it is not going to be installed
Depends: node-normalize-package-data (>= 2.4~) but 2.3.5-2 is to be installed
Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
Depends: node-resolve-from (>= 4.0~) but 2.0.0-1 is to be installed
Depends: node-npmlog (>= 4.1.2~) but 0.0.4-1 is to be installed
Depends: node-osenv (>= 0.1.5~) but 0.1.0-1 is to be installed
Depends: node-read-package-json (>= 2.0.13~) but 1.2.4-1 is to be installed
Depends: node-request (>= 2.83~) but 2.26.1-1 is to be installed
Depends: node-retry (>= 0.10.1~) but 0.6.0-1 is to be installed
Depends: node-rimraf (>= 2.6.2~) but 2.5.4-2 is to be installed
Depends: node-semver (>= 5.5~) but 5.3.0-1 is to be installed
Depends: node-sha (>= 2.0.1~) but 1.2.3-1 is to be installed
Depends: node-slide (>= 1.1.6~) but 1.1.4-1 is to be installed
Depends: node-strip-ansi (>= 4.0~) but 3.0.1-1 is to be installed
Depends: node-tar (>= 4.4~) but 2.2.1-1 is to be installed
Depends: node-boxen (>= 1.2.1~) but it is not going to be installed
Depends: node-latest-version (>= 3.0~) but it is not going to be installed
Depends: node-which (>= 1.3~) but 1.2.11-1 is to be installed
E: Unable to correct problems, you have held broken packages.
======================================================================
== Erreur à l'étape : Installation de npm car non présent
== Ligne 156
== La commande `sudo npm install -g npm' pose problème
== Le code de retour est 1
== Le message d'erreur :
sudo: npm: command not found
======================================================================
== Erreur à l'étape : Installation de Homebridge master, veuillez patienter svp
== Ligne 193
== La commande `sudo npm install --no-fund --no-package-lock --no-audit' pose problème
== Le code de retour est 1
== Le message d'erreur :
sudo: npm: command not found
======================================================================

Merci 
Bonne journée

**Comment by NebzHB** [comment]
Bonjour, ce problème a normalement été résolu.
si cela ne fonctionne toujours pas, je vous invite à faire un ticket sur le core pour leur demander de corriger le problème sur repo.jeedom.com
