### ISSUE TITLE
pi4 updated demon ko

### ISSUE THREAD

**Issue by cocapic** [NebzHB/jeedom_docs#12]
Bonjour,

le plugin demon est ko depuis maj du pi et reboot hier

log en pj

merci
[homebridge_daemon.zip](https://github.com/NebzHB/jeedom_docs/files/4671335/homebridge_daemon.zip)

**Comment by NebzHB** [comment]
Bonjour,

d'après les logs je ne vois pas de problème sur le démon (aucun crash) et je ne vois rien qui dit qu'il n'arrive pas à le lancer (depuis l'erreur de 8h55:01 il est lancé) et les dépendances ont bien tourné.

**Comment by cocapic** [comment]
Je sais rien dans les traces en mode debug mais toujours KO

**Comment by NebzHB** [comment]
Tu peux tenter ça :

```

ps -eo pid,command | grep ' homebridge'

```

**Comment by cocapic** [comment]
Pas eu le temps, malgré les logs le demon était bien KO et pas de homebridge

 

J’ai vider les logs du pi et reboot et depuis OK

 

Merci en tout cas

 

++

 

De : Nebz <notifications@github.com> 
Envoyé : samedi 23 mai 2020 22:24
À : NebzHB/jeedom_docs <jeedom_docs@noreply.github.com>
Cc : cocapic <cocapic@me.com>; Author <author@noreply.github.com>
Objet : Re: [NebzHB/jeedom_docs] pi4 updated demon ko (#12)

 

Tu peux tenter ça :

 
 
ps -eo pid,command | grep ' homebridge'
