### ISSUE TITLE
HomeBridge problème avec NPN

### ISSUE THREAD

**Issue by justefred** [NebzHB/jeedom_docs#13]
Bonjour,

après un problème lors de la mise à jour de Jeedom de la V3 vers V4, j'ai décider de refaire une install propre de Jeedom.
Lors de l'installation de Homebridge, il met impossible d'installer les dépendances.
J'ai essayé de downgrader NodeJS vers une version inférieur comme préciser dans le log, mais la commande fait appel à NPN que je ne peux installer car NodeJS est en version 10.
Votre aide serait la bienvenue.
N'hésitez pas à me dire ce dont vous avez besoin.

== Jeedom 4.0.60 sur Raspbian GNU/Linux 10 (buster)/armhf/armv7l/32bits aka 'RPI 3 B' avec nodeJS v10.21.0 et jsonrpc:enable et homebridge (stable) 2020-05-11 11:21:16
======================================================================
== 26/07/2020 22:04:12 == Installation des dépendances de homebridge
======================================================================
[  0% ] : Vérification des droits...
[  9% ] : Vérification des droits : [  OK  ]
[ 10% ] : Prérequis...
[ 19% ] : Prérequis : [  OK  ]
[ 20% ] : Mise à jour APT et installation des packages nécessaires...
[ 29% ] : Mise à jour APT et installation des packages nécessaires : [  OK  ]
[ 30% ] : Vérification de la version de NodeJS installée...
Version actuelle :
[ 39% ] : Vérification de la version de NodeJS installée : [  OK  ]
[ 40% ] : Installation de NodeJS 12...
KO, version obsolète à upgrader
Suppression du Nodejs existant et installation du paquet recommandé
Utilisation du dépot officiel
Version après install : v10.21.0
Version non suffisante, relancez les dépendances
[ 44% ] : Installation de NodeJS 12 : [  OK  ]
[ 45% ] : Installation de npm car non présent...
[ 49% ] : Installation de npm car non présent : [ERREUR]
[ 50% ] : Nettoyage anciens modules...
[ 59% ] : Nettoyage anciens modules : [  OK  ]
[ 60% ] : Installation de Homebridge master, veuillez patienter svp...
[ 79% ] : Installation de Homebridge master, veuillez patienter svp : [ERREUR]
[ 80% ] : Configuration Avahi...
[ 89% ] : Configuration Avahi : [  OK  ]
[ 90% ] : Nettoyage 1/2...
[ 94% ] : Nettoyage 1/2 : [  OK  ]
[ 95% ] : Nettoyage 2/2...
[ 99% ] : Nettoyage 2/2 : [  OK  ]
[100% ] : Terminé !
======================================================================
== KO == Erreur d'Installation
======================================================================
== Erreur à l'étape : Installation de npm car non présent
== Ligne 167
== La commande `sudo npm install -g npm' pose problème
== Le code de retour est 1
== Le message d'erreur :
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/npm failed, reason: unable to get local issuer certificate
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-26T20_06_51_413Z-debug.log
======================================================================
== Erreur à l'étape : Installation de Homebridge master, veuillez patienter svp
== Ligne 204
== La commande `sudo npm install --no-fund --no-package-lock --no-audit' pose problème
== Le code de retour est 1
== Le message d'erreur :
npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/mqtt failed, reason: unable to get local issuer certificate
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-26T20_07_39_402Z-debug.log
======================================================================

**Comment by NebzHB** [comment]
Bonjour,

Merci d'utiliser le bouton "Réparer et Réinstaller" dans la configuration du plugin homebridge.
