### ISSUE TITLE
Démon Homebridge ne démarre pas

### ISSUE THREAD

**Issue by Mathieu-Jacquier** [NebzHB/jeedom_docs#15]
Bonjour , 

J'utilise Jeedom via un raspy depuis quelques années sauf que j'ai toujours eu des soucis avec le plugin Homebridge. En effet ce plugin refuse de garder le Démon sur ok… Il passe 3/4 sec en vert et repasse en rouge.
J'ai déjà fait "réparer" réparer puis réinstaller" , supprimer le plugin puis réinstaller complètement le plugin, rien n'y fait .
Que puis je faire pour solutionner ce problème ? 

Merci d’avance pour vos conseils…

![tempsnip](https://user-images.githubusercontent.com/11523911/97047237-efe5b680-1578-11eb-9d77-129395572ad6.png)

[Fichiers_log.zip](https://github.com/NebzHB/jeedom_docs/files/5431494/Fichiers_log.zip)

**Comment by NebzHB** [comment]
Bonjour,

pouvez-vous fournir le log API de jeedom ?

il faut d'abord l'activer dans : Réglages > Système > Configuration > Logs > Logs > Api -> Debug
puis relancez le démon homebridge et ensuite dans Analyses > Logs > Api vous voyez le log.

**Comment by Mathieu-Jacquier** [comment]
[api.zip](https://github.com/NebzHB/jeedom_docs/files/5500824/api.zip)

Bonjour,
Vous le trouverez en pièce jointe
Cordialement
Mathieu

**Comment by NebzHB** [comment]
je n'ai rien reçu, logguez vous sur https://github.com/NebzHB/jeedom_docs/issues/15#issuecomment-722919885 et envoyez le log à cet endroit

**Comment by Mathieu-Jacquier** [comment]
[api.zip](https://github.com/NebzHB/jeedom_docs/files/5500825/api.zip)

**Comment by NebzHB** [comment]
Pour moi, il doit y avoir un équipement qui fait tout planter...

pour voir lequel, le plus simple est de désactiver toutes les pièces sauf une, et dans cette pièce désactiver tous les équipements sauf 1. puis relancez le démon, si le démon tient, ajoutez les équipement un par un pour déterminer lequel est fautif.

avez vous le plugin "abeille" ?

**Comment by NebzHB** [comment]
vous pouvez aussi attendre la mise à jour de ce soir/demain qui devrait indiquer un peu mieux l'erreur avec un log peut-etre plus parlant (ou bien vous pouvez tester avec le plugin en beta)

**Comment by Mathieu-Jacquier** [comment]
Merci ! 
J'ai pu ainsi déterminer une pièce puis des variables défaillante à savoir celles en lien avec le plugin Freebox OS et à présent tout fonctionne :)
