### ISSUE TITLE
Homebridge dependencies NOK

### ISSUE THREAD

**Issue by manoxx75** [NebzHB/jeedom_docs#16]
Impossible de start the dependencies. I have this message in my log but doesn't know how to interpret it
[2020-12-29 18:50:02][ERROR] : Veuillez exécuter le script : /bin/bash /var/www/html/plugins/homebridge/core/class/../../resources/install_homebridge.sh 192.168.1.35 master

**Comment by NebzHB** [comment]
Hi

Could you vive me more info ? It seems you're using ubuntu or something?  That message occurs when jeedom don't find "sudo".

**Comment by manoxx75** [comment]
I'm using Debian 10

**Comment by manoxx75** [comment]
just saw in the changeling that recent version has been published with some fix on nom. On my side it is saying that nom is not properly installed

**Comment by manoxx75** [comment]
change log sorry

**Comment by manoxx75** [comment]
npm not properly installed

**Comment by NebzHB** [comment]
Of course, that's the role of that script...

Install sudo, login in ssh in root then :

apt-get install sudo

Then retry to install the dependencies 

Envoyé de mon iPhone

**Comment by manoxx75** [comment]
thanks a lot for your support. Could you please clarify how I should install the dependencies. I added Homebridge plugin through the Jeedom Market

**Comment by NebzHB** [comment]
In plugins > communication > homebridge 

Then in dependencies you have a button to restart the install

Envoyé de mon iPhone

**Comment by manoxx75** [comment]
Unfortunately it doesn't work. Any other ideas ?

**Comment by NebzHB** [comment]
Please be more specific...

**Comment by manoxx75** [comment]
Same issue.Nothing happens when I relaunch the install of the dependencies and the same error message within the log
