### ISSUE TITLE
Plugin incompatible

### ISSUE THREAD

**Issue by fredip42** [NebzHB/jeedom_docs#18]
J'au un message d'erreur, le plugin est incompatible 32 bits, je voudrais un remboursement

**Comment by NebzHB** [comment]
Bonjour, aucune idée de quel plugin vous parlez mais c'est indiqué dans la description sur le Market qu'il n'est pas compatible avec 32 bits (sur i386 uniquement). Passez en 64 bits sur i386 et ça fonctionnera.

**Comment by NebzHB** [comment]
Comme vous pouvez le lire également ici : 
https://doc.jeedom.com/fr_FR/compatibility/

Jeedom en lui-même n'est pas compatible 32 bits.
![image](https://user-images.githubusercontent.com/28622481/113049896-79428a00-91a4-11eb-9a7e-f528622313f5.png)
