### ISSUE TITLE
Pb avec le plugin Homebridge

### ISSUE THREAD

**Issue by YSHD06** [NebzHB/jeedom_docs#19]
Bonjour
box jeedom installée chez un client depuis plus d'un an en 3.3.27
Homebridge ne fonctionne pas. Il n'avait pas été utlilisé auparavant sur cette box
Vu sur forum que le pb pouvait venir d'une version de NodeJS.
Version du plugin Homebridge 3.3.24
Version de NodeJS 8.9.4

Je demande un process pour mettre à jour à distance de préférence.
merci de votre aide
Marc de YourSmartHomeDesign (une dizaine de box pro installée)

**Comment by NebzHB** [comment]
Bonjour,

je suis le developpeur tier du plugin Homebridge.

quel est la version de linux debian ?

bien à vous,

Nebz

Le 2021-05-12 07:34, YSHD06 a écrit :

> Bonjour
> box jeedom installée chez un client depuis plus d'un an en 3.3.27
> Homebridge ne fonctionne pas. Il n'avait pas été utlilisé auparavant 
> sur cette box
> Vu sur forum que le pb pouvait venir d'une version de NodeJS.
> Version du plugin Homebridge 3.3.24
> Version de NodeJS 8.9.4
> 
> Je demande un process pour mettre à jour à distance de préférence.
> merci de votre aide
> Marc de YourSmartHomeDesign (une dizaine de box pro installée)
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].



Links:
------
[1] https://github.com/NebzHB/jeedom_docs/issues/19
[2]

**Comment by YSHD06** [comment]
Bonjour
9.4
Merci de ta rapidité

**Comment by NebzHB** [comment]
alors il faut faire une "réparation et réinstallation" (utilisez le bouton dans plugins > homebridge > bouton dans la configuration)

si ca ne fonctionne pas, fournissez le log homebridge_dep

**Comment by YSHD06** [comment]
Ok 
pour info, je lai déjà fait mais je recommence et fournis le log le cas échéant

**Comment by YSHD06** [comment]
Tu peux clore le ticket car après la relance que tu m'as demandée, je n'ai plus les messages d'erreurs que j'avais hier (ni dans homebridge_dep, ni dans le homebridge_daemon). un de mes gars ira vérifier sur place avec un iphone.
la version NodeJs est maintenant 14.17.0
merci de ton aide et de ta réactivité

**Comment by NebzHB** [comment]
version parfaite !

Le 2021-05-12 08:02, YSHD06 a écrit :

> Tu peux clore le ticket car après la relance que tu m'as demandée, je 
> n'ai plus les messages d'erreurs que j'avais hier (ni dans 
> homebridge_dep, ni dans le homebridge_daemon). un de mes gars ira 
> vérifier sur place avec un iphone.
> la version NodeJs est maintenant 14.17.0
> merci de ton aide et de ta réactivité
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].



Links:
------
[1] 
https://github.com/NebzHB/jeedom_docs/issues/19#issuecomment-839477518
[2]
