### ISSUE TITLE
jeedom homebridge dépendance non installé (debian 7)

### ISSUE THREAD

**Issue by ngm47** [NebzHB/jeedom_docs#2]
Bonjour,

j'ai un problème d'installation de dépendance, merci pour votre aide;
ci joint le logs: 

--0%
--10%
Lancement de l'installation/mise à jour des dépendances homebridge
--20%
Ign http://ftp.fr.debian.org jessie InRelease
Atteint http://ftp.fr.debian.org jessie-updates InRelease
Atteint http://security.debian.org jessie/updates InRelease
Atteint http://ftp.fr.debian.org jessie Release.gpg
Atteint http://ftp.fr.debian.org jessie Release
Réception de : 1 http://security.debian.org jessie/updates/main Sources [305 kB]
Réception de : 2 http://security.debian.org jessie/updates/non-free Sources [1 631 B]
Réception de : 3 http://security.debian.org jessie/updates/main i386 Packages [665 kB]
Réception de : 4 http://security.debian.org jessie/updates/non-free i386 Packages [4 549 B]
Réception de : 5 http://security.debian.org jessie/updates/main Translation-en [335 kB]
Réception de : 6 http://security.debian.org jessie/updates/non-free Translation-en [11,8 kB]
Atteint http://ftp.fr.debian.org jessie/main Sources
Atteint http://ftp.fr.debian.org jessie/non-free Sources
Atteint http://ftp.fr.debian.org jessie/main i386 Packages
Atteint http://ftp.fr.debian.org jessie/non-free i386 Packages
Atteint http://ftp.fr.debian.org jessie/main Translation-fr
Atteint http://ftp.fr.debian.org jessie/main Translation-en
Atteint http://ftp.fr.debian.org jessie/non-free Translation-en
W: Impossible de récupérer http://ftp.fr.debian.org/debian/dists/jessie-updates/InRelease  Impossible de trouver l'entrée « main/source/Sources » attendue dans le fichier « Release » : ligne non valable dans sources.list ou fichier corrompu
E: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
avahi-daemon est déjà la plus récente version disponible.
avahi-discover est déjà la plus récente version disponible.
avahi-utils est déjà la plus récente version disponible.
libavahi-compat-libdnssd-dev est déjà la plus récente version disponible.
dialog est déjà la plus récente version disponible.
libnss-mdns est déjà la plus récente version disponible.
apt-utils est déjà la plus récente version disponible.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 78 non mis à jour.
--30%
Version actuelle : v0.10.29
--40%
KO, version obsolète à upgrader
Suppression du Nodejs existant et installation du paquet recommandé
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
Le paquet « npm » n'est pas installé, et ne peut donc être supprimé
Les paquets suivants seront ENLEVÉS :
libc-ares2* libv8-3.14.5* nodejs*
0 mis à jour, 0 nouvellement installés, 3 à enlever et 78 non mis à jour.
Après cette opération, 7 747 ko d'espace disque seront libérés.
(Lecture de la base de données... 
(Lecture de la base de données... 5%
(Lecture de la base de données... 10%
(Lecture de la base de données... 15%
(Lecture de la base de données... 20%
(Lecture de la base de données... 25%
(Lecture de la base de données... 30%
(Lecture de la base de données... 35%
(Lecture de la base de données... 40%
(Lecture de la base de données... 45%
(Lecture de la base de données... 50%
(Lecture de la base de données... 55%
(Lecture de la base de données... 60%
(Lecture de la base de données... 65%
(Lecture de la base de données... 70%
(Lecture de la base de données... 75%
(Lecture de la base de données... 80%
(Lecture de la base de données... 85%
(Lecture de la base de données... 90%
(Lecture de la base de données... 95%
(Lecture de la base de données... 100%
(Lecture de la base de données... 55522 fichiers et répertoires déjà installés.)
Suppression de nodejs (0.10.29~dfsg-2) ...
Suppression de libc-ares2:i386 (1.10.0-2+deb8u2) ...
Purge des fichiers de configuration de libc-ares2:i386 (1.10.0-2+deb8u2) ...
Suppression de libv8-3.14.5 (3.14.5.8-8.1) ...
Purge des fichiers de configuration de libv8-3.14.5 (3.14.5.8-8.1) ...
Traitement des actions différées (« triggers ») pour man-db (2.7.0.2-5) ...
Traitement des actions différées (« triggers ») pour libc-bin (2.19-18+deb8u10) ...
--45%
Utilisation du dépot officiel
## Populating apt-get cache...
+ apt-get update
Ign http://ftp.fr.debian.org jessie InRelease
Atteint http://ftp.fr.debian.org jessie-updates InRelease
Atteint http://security.debian.org jessie/updates InRelease
Atteint http://ftp.fr.debian.org jessie Release.gpg
Atteint http://ftp.fr.debian.org jessie Release
Réception de : 1 http://security.debian.org jessie/updates/main Sources [305 kB]
Réception de : 2 http://security.debian.org jessie/updates/non-free Sources [1 631 B]
Réception de : 3 http://security.debian.org jessie/updates/main i386 Packages [665 kB]
Réception de : 4 http://security.debian.org jessie/updates/non-free i386 Packages [4 549 B]
Réception de : 5 http://security.debian.org jessie/updates/main Translation-en [335 kB]
Réception de : 6 http://security.debian.org jessie/updates/non-free Translation-en [11,8 kB]
Atteint http://ftp.fr.debian.org jessie/main Sources
Atteint http://ftp.fr.debian.org jessie/non-free Sources
Atteint http://ftp.fr.debian.org jessie/main i386 Packages
Atteint http://ftp.fr.debian.org jessie/non-free i386 Packages
Atteint http://ftp.fr.debian.org jessie/main Translation-fr
Atteint http://ftp.fr.debian.org jessie/main Translation-en
Atteint http://ftp.fr.debian.org jessie/non-free Translation-en
W: Impossible de récupérer http://ftp.fr.debian.org/debian/dists/jessie-updates/InRelease  Impossible de trouver l'entrée « main/source/Sources » attendue dans le fichier « Release » : ligne non valable dans sources.list ou fichier corrompu
E: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.
Error executing command, exiting
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
Les paquets supplémentaires suivants seront installés :
libc-ares2 libv8-3.14.5
Les NOUVEAUX paquets suivants seront installés :
libc-ares2 libv8-3.14.5 nodejs
0 mis à jour, 3 nouvellement installés, 0 à enlever et 78 non mis à jour.
Il est nécessaire de prendre 0 o/2 093 ko dans les archives.
Après cette opération, 7 747 ko d'espace disque supplémentaires seront utilisés.
Sélection du paquet libc-ares2:i386 précédemment désélectionné.
(Lecture de la base de données... 
(Lecture de la base de données... 5%
(Lecture de la base de données... 10%
(Lecture de la base de données... 15%
(Lecture de la base de données... 20%
(Lecture de la base de données... 25%
(Lecture de la base de données... 30%
(Lecture de la base de données... 35%
(Lecture de la base de données... 40%
(Lecture de la base de données... 45%
(Lecture de la base de données... 50%
(Lecture de la base de données... 55%
(Lecture de la base de données... 60%
(Lecture de la base de données... 65%
(Lecture de la base de données... 70%
(Lecture de la base de données... 75%
(Lecture de la base de données... 80%
(Lecture de la base de données... 85%
(Lecture de la base de données... 90%
(Lecture de la base de données... 95%
(Lecture de la base de données... 100%
(Lecture de la base de données... 55414 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../libc-ares2_1.10.0-2+deb8u2_i386.deb ...
Dépaquetage de libc-ares2:i386 (1.10.0-2+deb8u2) ...
Sélection du paquet libv8-3.14.5 précédemment désélectionné.
Préparation du dépaquetage de .../libv8-3.14.5_3.14.5.8-8.1_i386.deb ...
Dépaquetage de libv8-3.14.5 (3.14.5.8-8.1) ...
Sélection du paquet nodejs précédemment désélectionné.
Préparation du dépaquetage de .../nodejs_0.10.29~dfsg-2_i386.deb ...
Dépaquetage de nodejs (0.10.29~dfsg-2) ...
Traitement des actions différées (« triggers ») pour man-db (2.7.0.2-5) ...
Paramétrage de libc-ares2:i386 (1.10.0-2+deb8u2) ...
Paramétrage de libv8-3.14.5 (3.14.5.8-8.1) ...
Paramétrage de nodejs (0.10.29~dfsg-2) ...
update-alternatives: utilisation de « /usr/bin/nodejs » pour fournir « /usr/bin/js » (js) en mode automatique
Traitement des actions différées (« triggers ») pour libc-bin (2.19-18+deb8u10) ...
/var/www/html/plugins/homebridge/core/class/../../resources/install_homebridge.sh: ligne 137: npm : commande introuvable
Version actuelle : v0.10.29
--50%
--60%
Installation de Homebridge...
sudo: npm: command not found
--70%
--80%
--90%
Désactivation de avahi-daemon au démarrage...(il démarrera avec le daemon (on contourne le bug de la Smart du 1 jan 1970))
--95%
--100%
Installation des dépendances Homebridge terminée, vérifiez qu'il n'y a pas d'erreur

**Comment by NebzHB** [comment]
fixed since
