### ISSUE TITLE
Synchroniser les modules déjà présent dans homebridge

### ISSUE THREAD

**Issue by flavio-cbz** [NebzHB/jeedom_docs#21]
Bonjour, je viens d'acheter le plugin homebridge dans le but de récupérer mon module de détection d'ouverture / fermeture de porte parfaitement compatible homekit dans jeedom mais j'ai l'impression que le plugin est a sens unique : je peux envoyer des infos de jeedom a homekit mais pas l'inverse.
Ai-je raison ?

Merci d'avance pour votre réponse

**Comment by NebzHB** [comment]
Bonjour,
Vous confondez en effet Homebridge et Homekit.
Comme l'indique le sens des flèches sur l'image dans le market, le texte de description et la documentation du plugin, celui-ci sert en effet à envoyer les périphériques Jeedom dans Homekit et non l'inverse.

Par contre quel est votre module de détection d'ouverture/fermeture de porte ? s'il s'agit d'un Eve, grace au Eve Extend, vous pouvez le connecter à mon autre plugin Homekit Network Devices Control. Qui permet d'ajouter les périphérique Homekit RESEAU à Jeedom (j'ai bien dit réseau et pas bluetooth, le Eve Extend converti bluetooth en réseau dans mon exemple). vous pouvez lire la liste des périphériques compatible avec ce plugin ici : https://nebzhb.github.io/jeedom_docs/plugins/hkControl/fr_FR/#tocAnchor-1-7
