### ISSUE TITLE
plugins/homebridge/resources/node_modules est inclus dans tous les backups jeedom

### ISSUE THREAD

**Issue by CypZ** [NebzHB/jeedom_docs#22]
Hello,

Je sais pas si je suis sur le bon repo, jeedom / demande de support m'envoie ici ("ce plugin utilise un gestionnaire de demande de support --> accéder") et les "issues" sont pas ouvertes pour le repo NebzHB/homebridge-jeedom.

Mes backups jeedom deviennent de plus en plus lourds et en creusant je vois que c'est en majeure partie dû au plugin homebridge / au dossier node_modules, qui grossit à vue d'oeil.

Les paquets npm installés / compilés devraient être exclus du backup, ou bien ?

**Comment by NebzHB** [comment]
Bonjour,

je suis le developpeur du plugin Homebridge. Vous êtes au bon endroit 
pour la demande.

en tant que developpeur, le core de jeedom ne nous donne malheureusement 
pas la possibilité d'exclure des dossiers de notre plugin du backup.

je n'ai donc pas de solution pour vous.

Bien à vous,

Nebz

Le 2021-12-01 11:35, CypZ a écrit :

> Hello,
> 
> Je sais pas si je suis sur le bon repo, jeedom / demande de support 
> m'envoie ici ("ce plugin utilise un gestionnaire de demande de support 
> --> accéder") et les "issues" sont pas ouvertes pour le repo 
> NebzHB/homebridge-jeedom.
> 
> Mes backups jeedom deviennent de plus en plus lourd et en creusant je 
> vois que c'est en majeure partie dû au plugin homebridge / au dossier 
> node_modules, qui grossit à vue d'oeil, voir screenshot.
> [1]
> 
> Les paquets npm installés / compilés devraient être exclus du backup, 
> ou bien ?
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].



Links:
------
[1] 
https://user-images.githubusercontent.com/18141587/144219149-669a5406-05b3-4781-811e-590ac27cf88f.png
[2] https://github.com/NebzHB/jeedom_docs/issues/22
[3]

**Comment by CypZ** [comment]
Merci pour votre retour rapide, 

Cordialement,
