### ISSUE TITLE
Impossible de fonctionner Xiaomi talk si Jeedom full HTTPS

### ISSUE THREAD

**Issue by Leduc017** [NebzHB/jeedom_docs#24]
Bonjour,

J'utilise le plugin Xiaomi talk depuis 2 ans sans problème, mais j'ai récemment bien sécurisé mon jeedom, et je me rends compte que ce plugin nécessite jeedom de tourner en http.
Je ne comprends pas pourquoi ne serait-il pas possible d'accepter aussi de l'https qui est tout de même un standard désormais.
Je suis prêt à aider pour que cela fonctionne si besoin.
Sinon ce plug-in est super ! et je ne rencontre pas le fameux bug pour ma part!

Merci par avance pour la réponse.

Cordialement,
Julien

Jeedom stable v4.1.28

**Comment by NebzHB** [comment]
Bonjour,

Ce n'est malheureusement pas possible, en fait, je donne à la gateway xiaomi une url ou celle-ci peut lire le fichier mp3 à jouer. et lorsqu'on lui fourni une url avec https, celle-ci ne l'accepte pas (voir message log : "HTTPS en interne non supporté par Xiaomi"). le problème vient donc plutot de la gateway que du plugin.

mais en soit, ce n'est pas très grave, car du https en interne avec un certificat auto-signé n'a pas bcp de sens, et les outils genre letsencrypt permettent de faire une différence entre interne et externe.

intéressant par contre de voir que vous n'avez pas le bug, utilisez vous les "jingles" ?
