### ISSUE TITLE
Dependance installation issuer

### ISSUE THREAD

**Issue by fabrice9068** [NebzHB/jeedom_docs#26]
Hi
I'm not able to install the dependances for Homebridge, having the following error:
"== La commande `sudo apt-get --allow-releaseinfo-change update' pose problème"

(see attached)
[homebridge_dep.txt](https://github.com/NebzHB/jeedom_docs/files/8132806/homebridge_dep.txt)

Thanks for the help

**Comment by NebzHB** [comment]
Dear,

Jeedom v3 is not supported anymore. Please update soon !

Anyway i did updated the plugin to fix that issue, Please update the plugin.

BR's

Nebz

Envoyé de mon iPhone
