### ISSUE TITLE
Disparition du plugin hkControl

### ISSUE THREAD

**Issue by Marcobocram** [NebzHB/jeedom_docs#27]
[hkControl_deamon.txt](https://github.com/NebzHB/jeedom_docs/files/8462693/hkControl_deamon.txt)
[hkControl.txt](https://github.com/NebzHB/jeedom_docs/files/8462694/hkControl.txt)

Bonjour,
J'ai acheté un module iDiamant de Netatmo/Legrand pour pouvoir piloter mes 9 volets Bubendorff individuellement. Depuis environ 3 semaines j'ai des problèmes avec le plugin hkControl. J'ai essayé de me débrouiller tout seul depuis ce temps-là en lisant tout ce que j'ai trouvé sur ce sujet mais sans grand résultat.
Ce matin le plugin avait disparu (il n'était plus dans le menu "protocole domotique") alors qu'il était encore là hier soir lorsque les volets se sont fermés. Ce n'est pas la première fois que ça arrive mais jusque-là il était dans le menu et il fallait que je le réactive. Cette fois ci je l'ai retrouvé dans la liste des plugins dans gestions des plugins et j'ai pu le réactiver…
Le problème c'est que je ne peux absolument pas compter sur la gestion automatique de mes volets.

Je suis en version 4.2.14 de Jeedom.

**Comment by NebzHB** [comment]
Bonjour,


tout fonctionne bien dans les logs, sans plus d'information sur votre problème je ne peux vous aider...

1. il faudrait donner plus d'informations que "j'ai des problèmes"

2. un plugin ne se désactive pas tout seul, ca ne peut être fait que manuellement.


Bien à vous,

Nebz

**Comment by Marcobocram** [comment]
Bonjour,

Merci pour votre réponse.

Le problème est le fait qu’à plusieurs reprises ces derniers jours le plugin hkControl passait tout seul en « inactif », sans que j’intervienne, et la plupart du temps de nuit si bien que le matin les volets ne s’ouvraient plus sur un déclanchement de présence. Depuis j’ai dû déplacer temporairement mon module iDiamant le temps de faire des travaux, sans le rapprocher de la box internet et le phénomène n’est pas encore réapparu… J’attends donc de remettre tout dans la même configuration  pour voir si cela se reproduit, mais j’ai l’impression que par moment le module iDiamant perdait temporairement sa connexion wifi et ça créait un problème dans le plugin hkControl.

Cordialement,

Marc

 

De : Nebz ***@***.***> 
Envoyé : jeudi 14 avril 2022 10:10
À : NebzHB/jeedom_docs ***@***.***>
Cc : Marcobocram ***@***.***>; Author ***@***.***>
Objet : Re: [NebzHB/jeedom_docs] Disparition du plugin hkControl (Issue #27)

 

Bonjour,

tout fonctionne bien dans les logs, sans plus d'information sur votre problème je ne peux vous aider...

1.	il faudrait donner plus d'informations que "j'ai des problèmes"
2.	un plugin ne se désactive pas tout seul, ca ne peut être fait que manuellement.

Bien à vous,

Nebz

**Comment by NebzHB** [comment]
Bonjour,

En cas de perte wifi, le plugin hkControl tente de se reconnecter (mais je ne vois pas cela dans les logs fournis). Comme dit précédemment, il n'y a rien dans le plugin qui désactive celui-ci dans jeedom. Cela vient peut-etre d'un mécanisme interne à jeedom que je ne connais pas mais le plugin n'en est pas responsable.

Bien à vous,
Nebz

**Comment by Marcobocram** [comment]
Ce soir le plug-in n'a pas fonctionné, il était inactivé une fois de plus sans doute après 16h20 d'après les logs. Je l'ai réactivé mais cette fois-ci ça n'a pas suffit. Impossible de remettre en route mes scénarios de fermeture des volets. Je les ai fermés avec l'appli Home + Control. Et ça marche bien. J'ai du mal à comprendre que l'on ne puisse pas faire pareil avec Jeedom.
Je vois des erreurs dans les logs, "TypeError: Cannot read property" dans _daemon, et des problèmes d'installation dans _dep. Mais ça ne m'éclaire pas.

[hkControl_deamon.txt](https://github.com/NebzHB/jeedom_docs/files/8578043/hkControl_deamon.txt)
[hkControl.txt](https://github.com/NebzHB/jeedom_docs/files/8578047/hkControl.txt)
[hkControl_dep.txt](https://github.com/NebzHB/jeedom_docs/files/8578050/hkControl_dep.txt)

**Comment by NebzHB** [comment]
Bonjour,

concernant les dépendances, il faut faire un ticket chez jeedom (sur le core) pour le problème : 
```
 W: GPG error: https://repo.jeedom.com/odroid stable InRelease: The following signatures were invalid: EXPKEYSIG F9EB92D05446446C Jeedom
E: The repository 'http://repo.jeedom.com/odroid stable InRelease' is not signed.
```
cela résoudra ce problème.

concernant le démon, il faut évidemment le mettre en DEBUG et pas en info... sinon je n'ai pas les informations qu'il me faut.
de ce que je peux voir, à 26-04-2022 16:27:32 il y a une erreur mais non blocante, qui vient probablement d'une déconnexion du wifi de votre iDiamant, veuillez résoudre votre problème wifi.

et à nouveau à 27-04-2022 16:20:36 (quasi la même heure !!!) il y a un nouveau problème, mais le démon ne parvient pas à se reconnecter correctemeent à l'équipement. Encore un problème wifi.

c'est étrange d'avoir le problème quasi à la meme heure deux jours de suite, n'auriez vous pas qqch à cette heure là ?

**Comment by NebzHB** [comment]
Aucun retour, je cloture

**Comment by carmobocram** [comment]
J'ai réinstallé Jeedom et l'application, ça a marché un temps et depuis quelques jours les problèmes reviennent... C'est désespérant.
J'ai ouvert le #28

**Comment by NebzHB** [comment]
Bonjour,

tout fonctionne bien dans les logs, sans plus d'information sur votre 
problème je ne peux vous aider...

1. il faudrait donner plus d'informations que "j'ai des problèmes"

2. un plugin ne se désactive pas tout seul, ca ne peut être fait que 
manuellement.

Bien à vous,

Nebz

Le 2022-04-11 11:15, Marcobocram a écrit :

> hkControl_deamon.txt [1]
> hkControl.txt [2]
> 
> Bonjour,
> J'ai acheté un module iDiamant de Netatmo/Legrand pour pouvoir piloter 
> mes 9 volets Bubendorff individuellement. Depuis environ 3 semaines 
> j'ai des problèmes avec le plugin hkControl. J'ai essayé de me 
> débrouiller tout seul depuis ce temps-là en lisant tout ce que j'ai 
> trouvé sur ce sujet mais sans grand résultat.
> Ce matin le plugin avait disparu (il n'était plus dans le menu 
> "protocole domotique") alors qu'il était encore là hier soir lorsque 
> les volets se sont fermés. Ce n'est pas la première fois que ça arrive 
> mais jusque-là il était dans le menu et il fallait que je le réactive. 
> Cette fois ci je l'ai retrouvé dans la liste des plugins dans gestions 
> des plugins et j'ai pu le réactiver...
> Le problème c'est que je ne peux absolument pas compter sur la gestion 
> automatique de mes volets.
> 
> Je suis en version 4.2.14 de Jeedom.
> 
> --
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>



Links:
------
[1] 
https://github.com/NebzHB/jeedom_docs/files/8462693/hkControl_deamon.txt
[2] https://github.com/NebzHB/jeedom_docs/files/8462694/hkControl.txt
[3] https://github.com/NebzHB/jeedom_docs/issues/27
[4]

**Comment by Marcobocram** [comment]
Bonsoir,

Le phénomène s’est reproduit cet après-midi alors que je n’étais pas là. Les log s’arrêtent à 14h24 (à la fin du fichier hkControl). Dans les logs hkControl_deamon il y a des traces assez incompréhensibles pour moi après 14h24. Elles reprennent à 20 :16 lorsque j’ai réactivé le plugin.

Comment dès lors présenter ce problème à Jeedom alors qu’il semble qu’il y ait un problème autour de ‘removeAllListeners’ ?

Cordialement

Marc

 

De : Nebz ***@***.***> 
Envoyé : vendredi 15 avril 2022 07:51
À : NebzHB/jeedom_docs ***@***.***>
Cc : Marcobocram ***@***.***>; Author ***@***.***>
Objet : Re: [NebzHB/jeedom_docs] Disparition du plugin hkControl (Issue #27)

 

Bonjour,

En cas de perte wifi, le plugin hkControl tente de se reconnecter. Comme dit précédemment, il n'y a rien dans le plugin qui désactive celui-ci dans jeedom. Cela vient peut-etre d'un mécanisme interne à jeedom que je ne connais pas mais le plugin n'en est pas responsable.

Bien à vous,
Nebz

**Comment by NebzHB** [comment]
Bonjour, que voulez-vous dire par la ?

"Comment dès lors présenter ce problème à Jeedom alors qu’il semble qu’il y ait un problème autour de ‘removeAllListeners’ ?"

Envoyé de mon iPhone

**Comment by Marcobocram** [comment]
BonjourCe sont des vieux messages auxquels vous répondez il me semble qu'ils datent du mois d'avril.J'ai continué à avoir des problèmes tout l'été avec HKcontrol. Le module iDiamant est déconnecté régulièrement de hkcontrol et la reconnexion se passe très mal car HKcontrol attend un "bonjour" qui n'arrive jamais mais pendant ce temps-là l'appli de Legrand continue à fonctionner donc j'en ai eu marre et avant-hier j'ai exploré une autre solution avec Alexa qui semble fonctionner donc je laisse tomber HKcontrol. Il doit y avoir trop de restrictions dans le code alors que le système reste opérationnel par ailleurs.Dommage.Bonne continuation Marc Berrod Obtenir Outlook pour AndroidDe : Nebz ***@***.***>Envoyé : mardi 11 octobre 2022, 17:43À : NebzHB/jeedom_docs ***@***.***>Cc : Marcobocram ***@***.***>; Author ***@***.***>Objet : Re: [NebzHB/jeedom_docs] Disparition du plugin hkControl (Issue #27)

Bonjour, que voulez-vous dire par la ?



"Comment dès lors présenter ce problème à Jeedom alors qu’il semble qu’il y ait un problème autour de ‘removeAllListeners’ ?"



Envoyé de mon iPhone
