### ISSUE TITLE
Volet sous hkControl

### ISSUE THREAD

**Issue by carmobocram** [NebzHB/jeedom_docs#28]
Après avoir réinstallé Jeedom puis remis mon application, depuis 3 à 4 jours j'ai à nouveau des soucis avec mes volets Bubendorff iDiamant et hkControl.
Le module iDiamant passe offline réseau de temps en temps et après les volets ne répondent plus aux sollicitations. Alors qu'ils sont opérationnels avec l'appli Home+Control de Bubendorff.
Je vois dans les log le message SetAccessories brut : {"result":"ko","msg":{}} lorsque ça ne marche pas. Sinon j'ai ok quand ça marche. 
J'ai ajouté un redémarrage du daemon dès que le module iDiamant passe offline mais ça ne règle pas le problème. Je ne vois pas comment remettre le système en état de marche lorsque ça arrive. 

[hkControl-3.log](https://github.com/NebzHB/jeedom_docs/files/8788578/hkControl-3.log)
[hkControl_deamon-2.log](https://github.com/NebzHB/jeedom_docs/files/8788579/hkControl_deamon-2.log)

**Comment by NebzHB** [comment]
Bonjour, dans les dernier redémarrage que vous avez fait, on voit que la Prise control ne s'annonce plus sur le réseau. vérifiez votre réseau et que votre jeedom recoive bien le multicast. vous pouvez peut-etre aussi faire un désappairage puis un reset homekit sur l'équipement (voir documentation constructeur), puis un réappairage

**Comment by carmobocram** [comment]
J'ai constaté que le module iDiamant était vu off-line de temps en temps. J'ai donc écrit un scénario qui redémarre le daemon à chaque passage off-line mais ça ne règle pas le problème. Ce que je ne comprends pas c'est pourquoi l'application Home+ Control arrive à contrôler les volets dans tous les cas mais qu'avec Jeedom non. Le fait que iDiamant passe en off-line réseau, pour une raison que j'ignore, fait que le daemon doit considérer qu'il ne marche pas alors que l'appli Home + Control essaie de recontacter le module pour finir par lui envoyer ses commandes.
Comment savoir si Jeedom reçoit le multicast ? Pourquoi j'ai des déconnexions ?

![Historique déconnexions](https://user-images.githubusercontent.com/48419757/170892652-4587350a-0943-47d3-a939-f4f27423499d.png)

**Comment by NebzHB** [comment]
`Ce que je ne comprends pas c'est pourquoi l'application Home+ Control arrive à contrôler les volets dans tous les cas mais qu'avec Jeedom non`

car ce n'est pas le même protocol

`Comment savoir si Jeedom reçoit le multicast ?`

en connaissant votre réseau, vous devez savoir ceci. ou consultez votre informaticien.

Il y a une nouvelle version depuis hier qui permet de forcer les reconnections, l'avez-vous testé ?

**Comment by carmobocram** [comment]
J'ai donc installé la nouvelle version et curieusement ça a l'air de fonctionner beaucoup mieux. Je n'ai pas eu beaucoup de temps ces 2 derniers jours pour le vérifier complètement, il faudrait que je supprime le redémarrage du daemon en cas de offline réseau du iDiamant pour voir, mais cette nouvelle version semble prometteuse.
Quand au multicast je suis derrière une Livebox ADSL qui ne sert qu'à me connecter à Internet, je n'ai pas de box TV et je n'ai rien vu dans le programme de gestion de cette Livebox qui me permette de paramétrer ce genre de configuration.

**Comment by carmobocram** [comment]
J'ai eu un petit contre-temps ce matin, 2 volets ne se sont pas fermés ce matin vers 10:45. Pourtant il n'y a pas eu de déconnexion de iDiamant, ça marchait bien depuis l'installation de la nouvelle version.

[hkControl_deamon-5.log](https://github.com/NebzHB/jeedom_docs/files/8823665/hkControl_deamon-5.log)
[hkControl-5.log](https://github.com/NebzHB/jeedom_docs/files/8823670/hkControl-5.log)
.

**Comment by NebzHB** [comment]
![image](https://user-images.githubusercontent.com/28622481/171790982-e97ba866-c190-4d19-b727-3146c82f2263.png)
On voit très bien que la prise control a envoyé un aurevoir juste avant à 10:28, sans nouveau "bonjour" qu'elle a seulement envoyé à 11h04.
il y a donc bien eu une déconnexion ou un problème réseau.

mettez à jour le plugin, j'ai ajouté un message plus clair dans les logs si on tente de faire une action et que l'équipement n'a pas dit "Bonjour"

**Comment by carmobocram** [comment]
Depuis que j'ai installé la version du 3/6 le 6/6 à 13:01, je constate une très nette amélioration du Plug-in !
Je n'ai eu que 2 "Offline réseau" sur le iDiamant, évènement sur lequel je redémarre le Daemon. Je ne sais pas si c'est nécessaire, je vais faire le test sans.
Par contre dans les log à 9:59:07 il y a eu un arrêt du daemon non dû à une perte réseau, initiée par Jeedom. Le plug-in ne redémarre que 14 mn plus tard sans mon intervention, ça me parait bien long !
D'autre part le support Jeedom a corrigé le problème d'installation des dépendances hier 8/6.
Je crois que l'on est sur la bonne voie pour que ça fonctionne.

![offline réseau](https://user-images.githubusercontent.com/48419757/172794972-4a1bec39-6abd-40ef-971e-1fc898ba6047.png)
[hkControl-7.log](https://github.com/NebzHB/jeedom_docs/files/8868328/hkControl-7.log)
[hkControl_deamon-7.log](https://github.com/NebzHB/jeedom_docs/files/8868330/hkControl_deamon-7.log)
[hkControl_dep-7.log](https://github.com/NebzHB/jeedom_docs/files/8868343/hkControl_dep-7.log)

**Comment by NebzHB** [comment]
[08-06-2022 19:50:19][INFO] : Recu de jeedom: Demande d'arret

là dessus je n'ai aucun controle, c'est un arret du démon fait par le 
core de jeedom (ou par vous en arretant le démon manuellement).

pour la relance non plus aucun controle c'est la tache planifiée "cron 
plugins" du core qui s'en occupe.

je cloture donc la demande comme on a fait le tour :)

bien à vous

Le 2022-06-09 10:23, carmobocram a écrit :

> Depuis que j'ai installé la version du 3/6 le 6/6 à 13:01, je constate 
> une très nette amélioration du Plug-in !
> Je n'ai eu que 2 "Offline réseau" sur le iDiamant, évènement sur lequel 
> je redémarre le Daemon. Je ne sais pas si c'est nécessaire, je vais 
> faire le test sans.
> Par contre dans les log à 9:59:07 il y a eu un arrêt du daemon non dû à 
> une perte réseau, initiée par Jeedom. Le plug-in ne redémarre que 14 mn 
> plus tard sans mon intervention, ça me parait bien long !
> D'autre part le support Jeedom a corrigé le problème d'installation des 
> dépendances hier 8/6.
> Je crois que l'on est sur la bonne voie pour que ça fonctionne.
> 
> [1]
> hkControl-7.log [2]
> hkControl_deamon-7.log [3]
> hkControl_dep-7.log [4]
> 
> --
> Reply to this email directly, view it on GitHub [5], or unsubscribe 
> [6].
> You are receiving this because you commented.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://user-images.githubusercontent.com/48419757/172794972-4a1bec39-6abd-40ef-971e-1fc898ba6047.png
[2] https://github.com/NebzHB/jeedom_docs/files/8868328/hkControl-7.log
[3] 
https://github.com/NebzHB/jeedom_docs/files/8868330/hkControl_deamon-7.log
[4] 
https://github.com/NebzHB/jeedom_docs/files/8868343/hkControl_dep-7.log
[5] 
https://github.com/NebzHB/jeedom_docs/issues/28#issuecomment-1150823153
[6]
