### ISSUE TITLE
Erreur homebridge

### ISSUE THREAD

**Issue by mar20pinpin** [NebzHB/jeedom_docs#29]
Bonjour,

Je n'arrive pas à créer les dépendances homebridge.

Merci d'avance
[homebridge_dep (1).docx](https://github.com/NebzHB/jeedom_docs/files/8894532/homebridge_dep.1.docx)

**Comment by NebzHB** [comment]
Bonjour,

vous n'avez pas fourni le log complet (il s'arette à 50%). je ne peux pas vous aider.

**Comment by mar20pinpin** [comment]
Ok désolé voici la liste complète
[homebridge_dep (4).docx](https://github.com/NebzHB/jeedom_docs/files/8903755/homebridge_dep.4.docx)
.

**Comment by NebzHB** [comment]
```
Err:6 https://oph.mdrjr.net/meveric all Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 216.155.132.189 443]
Hit:7 http://www.deb-multimedia.org buster InRelease
Err:8 https://oph.mdrjr.net/meveric buster Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 216.155.132.189 443]
```

c'est une erreur du à une source du core, vous devez faire un ticket sur le core et leur donner ce message d'erreur, ils vous le corrigeront.

**Comment by mar20pinpin** [comment]
Ok merci beaucoup!
