### ISSUE TITLE
[Plugin Homebridge] Accessoires non remontés dans Maison de l'IOS

### ISSUE THREAD

**Issue by aldo31** [NebzHB/jeedom_docs#3]
Bonjour,

Je n'arrive pas à configurer Maison sur mon iphone.
J'ai installé le plugin homeBridge dans jeedom,
le deamon est bien démarré,
les pièces et accéssoires à faire remontés bien cochés,

dans Maison, sur mon iPad qui fera le pont, j'ai créé le domicile,
scanérisé le flashcode de bridge et ajouté le "_repaired"

cependant aucun accessoires de jeedom ne remontent.
Pour mes tests, j'ai désactivé toutes les pièces,
puis je n'ai activé qu'une seule pièce avec un seul volet roulant. 

rien à faire, aucun accessoire ne remonte.

Je vous remercie par avance pour votre aide,

Nico

**Comment by NebzHB** [comment]
Merci de vérifier vos types génériques et la documentation du plugin
