### ISSUE TITLE
Impossible d'integrer homebridge dans maison

### ISSUE THREAD

**Issue by CJA26** [NebzHB/jeedom_docs#32]
Bonjour,

Suite au remplacement d'une LiveBox, la connexion de homebridge a été perdu.

j'ai supprimé, le pont depuis maison, supprimé la maison, pour tenter de repartie à neuf.
Même résultat, lorsque j'ajoute le homebrige dans les accessoires de maison, apres un temps d'attente, un pop up m'indique que celui est injoignable

J'ai installé une passerelle certifié homekit pour essayé, tout fonctionne bien.
J'en déduis donc que ce n'est pas une erreur Apple ou réseau

En parallèle, j'ai pu voir sur des forums de vérifier avec l'application discovery (ios), que jeedom étéit visible sur le service _hap._tcp., 
je vois bien le jeedom mais une erreur remonte quand je le selectionne? "An error occured while resolving a service"

Merci de votre aide.
Christopher

**Comment by NebzHB** [comment]
Bonjour, lancez une réparation dans la configuration du plugin et surtout gardez le nouveau nom !NebzEnvoyé de mon iPhoneLe 17 mars 2023 à 14:41, CJA26 ***@***.***> a écrit :﻿
Bonjour,
Suite au remplacement d'une LiveBox, la connexion de homebridge a été perdu.
j'ai supprimé, le pont depuis maison, supprimé la maison, pour tenter de repartie à neuf.
Même résultat, lorsque j'ajoute le homebrige dans les accessoires de maison, apres un temps d'attente, un pop up m'indique que celui est injoignable
J'ai installé une passerelle certifié homekit pour essayé, tout fonctionne bien.
J'en déduis donc que ce n'est pas une erreur Apple ou réseau
En parallèle, j'ai pu voir sur des forums de vérifier avec l'application discovery (ios), que jeedom étéit visible sur le service _hap._tcp.,
je vois bien le jeedom mais une erreur remonte quand je le selectionne? "An error occured while resolving a service"
Merci de votre aide.
Christopher

**Comment by CJA26** [comment]
J’ai tenté la réparation sans succès.
Ne fonctionnant pas j’ai complètement effacé le pont et même fini par supprimer la maison pour recommencer de zéro…

**Comment by NebzHB** [comment]
Évidemment la réparation doit s'accompagner de la suppression du pont comme indiqué dans le message !Sinon tentez de retirer l'ipv6 de la box et donc de la configurer comme votre précédente ( notamment pour tout ce qui concerne le multicast, mDNS, igmp snooping etc)Envoyé de mon iPhoneLe 17 mars 2023 à 19:10, CJA26 ***@***.***> a écrit :﻿
J’ai tenté la réparation sans succès.
Ne fonctionnant pas j’ai complètement effacé le pont et même fini par supprimer la maison pour recommencer de zéro…

**Comment by NebzHB** [comment]
Vous devez absolument être dans le même réseau sur votre iPhone et jeedom, pas de routage , etc

**Comment by NebzHB** [comment]
Pensez aussi à redémarrer jeedom, les iPhone, iPad, la box et les concentrateurs

**Comment by CJA26** [comment]
Oui bien sur, tout à été redémarré…

Tout est sur le même réseau, sans répéteur ou autre sous réseau…

chose que je n’ai pas précisé, homebridge refuse également de se mettre à jour…

**Comment by CJA26** [comment]
> Évidemment la réparation doit s'accompagner de la suppression du pont comme indiqué dans le message !Sinon tentez de retirer l'ipv6 de la box et donc de la configurer comme votre précédente ( notamment pour tout ce qui concerne le multicast, mDNS, igmp snooping etc)Envoyé de mon iPhoneLe 17 mars 2023 à 19:10, CJA26 ***@***.***> a écrit :﻿ J’ai tenté la réparation sans succès. Ne fonctionnant pas j’ai complètement effacé le pont et même fini par supprimer la maison pour recommencer de zéro… —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

J’y ai bien pensé, j’ai désactivé l’ipv6.
Je n’ai pas vu ces paramètres dans la livebox, mais comme évoqué les autre produits homekit fonctionne bien sur le réseau, ca doit donc pas venir de la config réseau…

**Comment by NebzHB** [comment]
"chose que je n’ai pas précisé, homebridge refuse également de se mettre à jour…"

alors il faut fournir les logs

**Comment by NebzHB** [comment]
` mais comme évoqué les autre produits homekit fonctionne bien sur le réseau, ca doit donc pas venir de la config réseau…`

tous les autres utilisateurs homebridge n'ont pas ce problème, ca doit donc pas venir de homebridge...

**Comment by CJA26** [comment]
Quels autres utilisateurs ?
Ca ne fonctionne pas et pour personne…

**Comment by NebzHB** [comment]
Tous les autres utilisateurs de homebridge et jeedom.

Le 2023-03-19 11:49, CJA26 a écrit :

> Quels autres utilisateurs ?
> Ca ne fonctionne pas et pour personne...
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you commented.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/NebzHB/jeedom_docs/issues/32#issuecomment-1475203655
[2]

**Comment by NebzHB** [comment]
c'était juste pour vous démontrer que votre phase n'avait pas bcp de sens. c'est pas parce qu'un produit fonctionne que tous doivent fonctionner.

mais fournissez les logs qu'on puisse avancer.

**Comment by NebzHB** [comment]
"chose que je n’ai pas précisé, homebridge refuse également de se mettre à jour…"

mm je viens d'y repenser, mais vous ne me parlez pas de dépendances dans cette phrase donc je parie que vous avez fait la mise à jour via l'interface config-ui-x ? il est indiqué quand vous ouvez cette interface qu'il ne faut pas le faire :
![image](https://user-images.githubusercontent.com/28622481/226176255-34c899f5-d486-4fcb-8390-1ba1e5e034ab.png)

si vous l'avez fait malgré tout, vous vous retrouvez donc avec deux homebridges sur le même système, relancez les dépendances, cela devrait résoudre votre problème et n'en laisser plus qu'une.

**Comment by CJA26** [comment]
Je n’ai pas pu encore retourné sur site, je vous tiens informé…

**Comment by CJA26** [comment]
Bonjour,
je n'ai pas pu retourner sur site, du coup j'ai supprimé et réinstallé homebridge à distance.
Ca fonctionne à nouveau...
