### ISSUE TITLE
GMP n'est pas bien installé, relancez vos dépendances

### ISSUE THREAD

**Issue by transervice** [NebzHB/jeedom_docs#34]
Bonjour, à la suite d'un changement de mémoire emc (de 8 à 16)  sur smart II ,ras sauf:  seul la dépendance homebridge est récalcitrante.
J'ai regardé les différents postes sur le sujet et après réinstallation du plugin et de nombreux redémarrages, j'ai toujours le même problème.
voici le log debug d'installation (avec une verification de certificat failed)

== Jeedom 4.3.17 sur Debian GNU/Linux 10 (buster)/arm64/aarch64/64bits aka 'smart' avec nodeJS  et jsonrpc:enable et homebridge (stable) 2023-04-21 07:27:05 (avant:stable/2023-04-03 09:03:16)
======================================================================
== 10/06/2023 06:24:09 == Installation des dépendances de homebridge
======================================================================

[  0% ] : Vérification des droits...
[  4% ] : Vérification des droits : [0sec] : [  OK  ]
[  5% ] : Mise à jour APT et installation des packages nécessaires...
[ 99% ] : Mise à jour APT et installation des packages nécessaires : [6sec] : [Erreur]
[100% ] : Terminé !

======================================================================
== KO == Erreur d'Installation [6sec]
======================================================================
== ANALYSE DES ERREURS...
== AUCUNE ERREUR CONNUE DÉTECTÉE
== Erreur à l'étape : Mise à jour APT et installation des packages nécessaires
== Ligne 160
== La commande `sudo apt-get update' pose problème
== Le code de retour est 100
== Le message d'erreur :
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://ftp.uk.debian.org/debian buster InRelease
Hit:3 http://ftp.uk.debian.org/debian buster-updates InRelease
Ign:4 https://oph.mdrjr.net/meveric all InRelease
Ign:5 https://oph.mdrjr.net/meveric buster InRelease
Err:6 https://oph.mdrjr.net/meveric all Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 216.155.132.189 443]
Err:7 https://oph.mdrjr.net/meveric buster Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 216.155.132.189 443]
Reading package lists...
E: The repository 'https://oph.mdrjr.net/meveric all Release' no longer has a Release file.
E: The repository 'https://oph.mdrjr.net/meveric buster Release' no longer has a Release file.

**Comment by NebzHB** [comment]
Bonjour, je n'avais pas vu votre demande avant, dasolé, mais aucun rapport avec homebridge ici, c'est le répository : https://oph.mdrjr.net/meveric qui pose problème qui n'est pas installé par homebridge.
