### ISSUE TITLE
Impossible d'appairer une connectivity kit box somfy

### ISSUE THREAD

**Issue by AD65AD65** [NebzHB/jeedom_docs#35]
Bonjour,
Le descriptif du plugin indiquait qu'il pouvait éventuellement fonctionner avec le connectivity kit box somfy
En fait il est impossible d'appairer du tout. Le format du code pin xxx.xx.xxx ne correspond pas au (apparement nouveau format) des ces box en xxxx.xxxx.xxxx.
J'estime avoir été trompé et avoir dépensé 6 euros pour rien.
Merci d'être assez aimable de me trouver une solution pour me rembourser.
Cdt
Alain

**Comment by NebzHB** [comment]
je vous ai répondu sur la communauté.
