### ISSUE TITLE
Attention : Vous êtes en Debian 10 Buster, ce système est déprecié ! Merci de mettre à jour votre distribution !!!

### ISSUE THREAD

**Issue by Brudith** [NebzHB/jeedom_docs#36]
Bonjour,
Suite à la mise à jour de :+1: 
=>  Jeedom version 4.4.7 le 19/06/2024
=>  Homebridge le 19/06/2024
A la suite de l'adresse IP Jeedom de connection, j'ai ce message qui est apparu sur la même ligne de mon adresse IP : 
"Attention : Vous êtes en Debian 10 Buster, ce système est déprecié ! Merci de mettre à jour votre distribution !!!"
Je viens de passer à la fibre optique depuis une quinzaine de jour, ma Box c'est Feebox Delta et ma Box Jeedom Atlas.
J'ai bien compris qu'il faille mettre Debian 10 à jour, mais comment faire c'est là que j'ai besoin d'aide, sachant que je suis pas un expert et qui plus un papy. Ma domotic fonctionne depuis plus de 4 ans maintenant sans aucun souci et là je me trouve face à un réel problème.
Je recherche un ou des spécialistes qui pourrait m'aider
Je vous en remercie par avance

**Comment by NebzHB** [comment]
Bonsoir, je suis le developpeur du plugin, pas de jeedom ou de debian, merci de contacter ces derniers pour votre support.
