### ISSUE TITLE
Mise à jour DEBIAN 11

### ISSUE THREAD

**Issue by Thomas69747** [NebzHB/jeedom_docs#37]
Bonjour,
En essayant de comprendre pourquoi Homebridge ne fonctionnait plus, je me suis rendu compte que le message suivant était affiché:
Vous êtes en Debian 10 Buster, ce système n'est plus supporté ! Merci de mettre à jour votre distribution !!!

Sur le forum ils disent de faire une demande de support...  Chose que je viens de faire..

Je vous remercie de votre aide..
PS: je ne suis pas informaticien ou programmeur... Besoin d'explication simple ;-)

Merci de votre compréhension

Thomas

**Comment by NebzHB** [comment]
Bonjour,Vous êtes sur le support Homebridge, pas le support jeedom. Contactez les pour mettre à jour votre système.Bien à vous,Nebz Envoyé de mon iPhoneLe 6 juil. 2024 à 18:37, Thomas69747 ***@***.***> a écrit :﻿
Bonjour,
En essayant de comprendre pourquoi Homebridge ne fonctionnait plus, je me suis rendu compte que le message suivant était affiché:
Vous êtes en Debian 10 Buster, ce système n'est plus supporté ! Merci de mettre à jour votre distribution !!!
Sur le forum ils disent de faire une demande de support...  Chose que je viens de faire..
Je vous remercie de votre aide..
PS: je ne suis pas informaticien ou programmeur... Besoin d'explication simple ;-)
Merci de votre compréhension
Thomas
