### ISSUE TITLE
Demande de mise à jour Debian 10 Buster

### ISSUE THREAD

**Issue by BD851** [NebzHB/jeedom_docs#38]
Bonjour,

Le plugin homebridge m'indique que je dois mettre à jour ma distribution debian 10 Buster. Il est indiqué sur le forum que je dois faire un ticket pour cela. Voilà qui est fait. Merci de vitre aide.

Bien cordialement,

Bruno DUIGOU
![Image 18-08-2024 à 18 57](https://github.com/user-attachments/assets/800c8838-2555-427c-9eac-9a3bc359c5a6)

**Comment by NebzHB** [comment]
Bonjour, comme indiqué vous ne devez pas faire le ticket sur le plugin Homebridge, je suis le développeur tiers de celui-ci et ne suis pas responsable de votre système. Faites un ticket sur la catégorie générale pour arriver chez jeedom.

**Comment by NebzHB** [comment]
Ah mais vous n'avez pas une smart, donc consultez communauté pour mettre à jour, la seule raison de faire un ticket c'est une smart... le reste vous pouvez mettre à jour vous même.
