### ISSUE TITLE
pluggin homebridge dans Jeedom

### ISSUE THREAD

**Issue by lcropage** [NebzHB/jeedom_docs#39]
bonjour, pouvez-vous me donner la version Debian 11 pour que mon pluggin Homebridge puisse fonctionner?
Merci

**Comment by NebzHB** [comment]
Bonjour, je ne comprends pas ce que vous me demandez...Le plugin est compatible debian 11 et 12. Sur jeedom 4.4 au minimum.Bien à vous,Nebz Envoyé de mon iPhoneLe 31 août 2024 à 09:26, lcropage ***@***.***> a écrit :﻿
bonjour, pouvez-vous me donner la version Debian 11 pour que mon pluggin Homebridge puisse fonctionner?
Merci

**Comment by NebzHB** [comment]
aucun retour, je considère donc que vous avez résolu votre problème.

**Comment by lcropage** [comment]
Bonjour, oui désolé j’étais partis en congès…

J’ai vu qu’il faut complètement updater mon raspberry, je vais m’y atteler 😊
