### ISSUE TITLE
Commande d'un état numérique par Homebridge

### ISSUE THREAD

**Issue by DomoPad** [NebzHB/jeedom_docs#4]
Dans le cadre d'un luminaire à variation, qui peut donc prendre deux états (éteint ou 0% et allumé entre 1 et 100%). il y a donc un slider un ''On'' et un ''Off''. Lorsque je crée un virtuel qui appelle un script à deux commandes. Le ''On'' rappelle le dernier état d'un luminaire (en commande http) et le ''Off'' éteint le luminaire (toujours en http), cela fonctionne parfaitement tant que je reste sur le virtuel jeedom. Lorsque je passe sur Homebridge, le ''On'' pousse un 100% à la place du dernier état (réglé par le slider). J'ai donc essayé de définir pour homebridge que le ''On'' ne soit pas un (type générique) ''lumière Bouton On'' mais un (type générique) ''Lumière toggle''. Cela ne fonctionne pas non plus. Aucun type générique jeedom ne fonctionne. On est donc obligé de passer par le slider pour avoir une autre valeurs que 0% ou 100%.

**Comment by NebzHB** [comment]
Il faut utiliser la variation de luminosité comme indiqué dans la documentation.
