### ISSUE TITLE
nodejs en erreur suite a une tentative de réparation NodeJS

### ISSUE THREAD

**Issue by OuiOui-95** [NebzHB/jeedom_docs#40]
Bonjour,

N'arrivant pas a mettre a jour hkControl j'ai tenté une  réparation NodeJS. cela a agravé la situation.
Nodejs est en erreur et le manager MQTT ne démarre plus.
![jeedom](https://github.com/user-attachments/assets/78046982-e138-48a9-a394-3f1266da95f7)

**Comment by NebzHB** [comment]
Bonjour, sans log de dépendance je ne peux pas vous aider.

**Comment by OuiOui-95** [comment]
== Jeedom 4.4.19 sur Debian GNU/Linux 10 (buster)/arm64/aarch64/64bits aka 'Atlas' avec nodeJS  et jsonrpc:enable et hkControl (stable) 2024-09-12 16:06:59 (avant:stable/2024-03-22 10:35:29)
======================================================================
== 22/11/2024 22:15:04 == Installation des dépendances de hkControl
======================================================================
[  0% ] : Vérification des droits...
[  4% ] : Vérification des droits : [0sec] : [  OK  ]
[  5% ] : Mise à jour APT et installation des packages nécessaires...
[ 99% ] : Mise à jour APT et installation des packages nécessaires : [1sec] :  ERROR 
[100% ] : Terminé !
======================================================================
==KO== Erreur d'Installation [1sec]
======================================================================
== ANALYSE DES LOGS...
== AUCUNE ERREUR CONNUE DÉTECTÉE
== Erreur à l'étape : Mise à jour APT et installation des packages nécessaires
== Ligne 225
== La commande `sudo apt-get update' pose problème
== Le code de retour est 143
== Le message d'erreur :
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://archive.debian.org/debian buster-backports InRelease
Hit:3 http://security.debian.org buster/updates InRelease
Hit:4 http://deb.debian.org/debian buster-updates InRelease
Hit:5 https://deb.nodesource.com/node_18.x nodistro InRelease
======================================================================

**Comment by OuiOui-95** [comment]
== Jeedom 4.4.19 sur Debian GNU/Linux 10 (buster)/arm64/aarch64/64bits aka 'Atlas' avec nodeJS  et jsonrpc:enable et hkControl (stable) 2024-09-12 16:06:59 (avant:stable/2024-03-22 10:35:29)
======================================================================
== 22/11/2024 22:24:13 == Installation des dépendances de hkControl
======================================================================
[  0% ] : Vérification des droits...
[  4% ] : Vérification des droits : [0sec] : [  OK  ]
[  5% ] : Mise à jour APT et installation des packages nécessaires...
[  9% ] : Mise à jour APT et installation des packages nécessaires : [11sec] : [  OK  ]
[ 10% ] : Prérequis...
[ 14% ] : Prérequis : [0sec] : [  OK  ]
[ 15% ] : Installation des packages nécessaires...
[ 19% ] : Installation des packages nécessaires : [2sec] : [  OK  ]
[ 20% ] : Vérification du système...
[ 99% ] : Vérification du système : [1sec] : [  OK  ]
[100% ] : Terminé !
======================================================================
==KO== Erreur d'Installation [14sec]
======================================================================
== ANALYSE DES LOGS...
== AUCUNE ERREUR CONNUE DÉTECTÉE
======================================================================
==  ERROR  ATTENTION Debian 10 Buster n'est officiellement plus supportée depuis le 30 juin 2024, merci de mettre à jour votre système en version plus récente de Debian !!!
==  ERROR  Les dépendances sont bloquées afin d'éviter tout problème, soit hkControl fonctionne et donc on y touche plus tant qu'il tourne, soit il ne fonctionne plus et donc il faut mettre à jour votre système en version plus récente de Debian.
==  ERROR  Jeedom 4.4.17 est passé à NodeJS 20 qui est incompatible avec Debian 10. PLUS AUCUN SUPPORT NE PEUT ÊTRE FAIT !!! Migrez donc au plus vite !
======================================================================

**Comment by NebzHB** [comment]
Vous avez donc votre réponse.

**Comment by OuiOui-95** [comment]
Merci.
