### ISSUE TITLE
Dependances issue on Homebridge

### ISSUE THREAD

**Issue by YomoShitsu** [NebzHB/jeedom_docs#5]
Hello, 
I bought Homebridge on Jeedom v3.3.38 installed on Debian 8. 
My machine is up to date. 
When I try to install dependances, it doesn't works and I don't find any logs...
Can you help please ? 
And if you need some logs in specific folder, don't hesitate ! 

Thank you in advance for your support

Kind Regards

Nicolas A.

**Comment by NebzHB** [comment]
Dear,

yes i need homebridge_dep logs, if it doesn't appears, please contact Jeedom Support.

**Comment by NebzHB** [comment]
cloture car pas de réponse. merci de passer par communauté pour un support plus rapide.
closing the issue because no reply. please use community for a faster support.
