### ISSUE TITLE
Problème avec le plugin homebridge-bravia : cookiepath 

### ISSUE THREAD

**Issue by Tm23mT** [NebzHB/jeedom_docs#7]
Bonjour,

Je souhaiterais utiliser le plugin homebridge-bravia pour accéder au contrôle de mon téléviseur dans Homekit, j'ai réussi à configurer mon téléviseur Sony, néanmoins quand je relance le daemon j'ai l'erreur suivante : 

[BraviaPlatform] Error writing cookie file to undefined. Add a cookiepath parameter to config.json to specify the path. Note that you specify the FILE path, not the folder.

Ci joint le contenu en .jsom:

{
    "platform": "BraviaPlatform",
    "tvs": [
      {
        "name": "Sony Bravia",
        "ip": "10.0.0.27",
        "soundoutput": "speaker",
        "tvsource": "tv:dvbs",
        "applications": false,
        "cookiepath": "/Homebridge/sonycookie",
        "sources": [
          "extInput:hdmi",
          "extInput:component",
          "extInput:scart",
          "extInput:cec",
          "extInput:widi"
        ]
      }
    ]
  }

Je ne connais pas exactement le chemin vers le fichier /sonycookie. J'ai donc écris "/Homebridge/sonycookie" mais ce n'ai pas correct. Comment le trouver dans l'interface Jeedom. Ou peut-on voir le système de fichier du Jeedom?

Merci d'avance pour votre réponse

Bien cordialement

Thibault

**Comment by NebzHB** [comment]
Bonjour,

je ne fais pas le support pour les plugins tiers de homebridge.

ce dossier est un dossier quelconque ou il va stocker le cookie de sony je suppose... assurez vous que www-data ait des accès à ce dossier. si vous ne savez pas ou le créer, merci de faire appel au support jeedom qu'ils vous indiquent un dossier adéqua.

**Comment by NebzHB** [comment]
cloture car pas de réponse. merci de passer par communauté pour un support plus rapide.
