### ISSUE TITLE
homebridge

### ISSUE THREAD

**Issue by Akysis** [NebzHB/jeedom_docs#9]
Avec la mise jour V4 de jeedom, les dépendances sont toujours NOK

**Comment by NebzHB** [comment]
sans plus d'information je ne peux vous aider, sachez cependant que homebridge fonctionne sans problème avec Jeedom V4.

**Comment by NebzHB** [comment]
aucun retour depuis 18 jours, je cloture

**Comment by Gouttedo** [comment]
Bonjour,
Moi c'est le demon qui est NOK.
Comment pouvons nous procéder ?
